name:                composite-xstep
version:             0.1.0.0
git:                 https://gitlab.com/homotopic-tech/composite-xstep
license:             MIT
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            ReaderT transformer pattern for higher kinded composite data.
category:            Data Structures

description:         ReaderT transformer pattern for higher kinded composite data.

dependencies:
- base >= 4.7 && < 5
- composite-base
- vinyl

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  source-dirs: src
